# Workflow to create exports
name: Create Exports

on:
  [push, pull_request]

jobs:
  export:
    name: Create Exports
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'tools platform-tools build-tools;33.0.2 platforms;android-33 cmdline-tools;latest cmake;3.10.2.4988404 ndk;23.2.8568313'
        
      - name: Generate Random Keystore
        run: |
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore template.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999 -deststoretype pkcs12

      - name: Patch Keystore Settings
        run: |
          sed -i "s@^keystore/debug=\"\"@keystore/debug=\"template.keystore\"@g" export_presets.cfg
          sed -i "s@^keystore/debug_user=\"\"@keystore/debug_user=\"androiddebugkey\"@g" export_presets.cfg
          sed -i "s@^keystore/debug_password=\"\"@keystore/debug_password=\"android\"@g" export_presets.cfg
          sed -i "s@^keystore/release=\"\"@keystore/release=\"template.keystore\"@g" export_presets.cfg
          sed -i "s@^keystore/release_user=\"\"@keystore/release_user=\"androiddebugkey\"@g" export_presets.cfg
          sed -i "s@^keystore/release_password=\"\"@keystore/release_password=\"android\"@g" export_presets.cfg

      #- name: Manually Install Android Templates
      #  run: |
      #    wget -nv https://github.com/godotengine/godot/releases/download/4.0.2-stable/Godot_v4.0.2-stable_export_templates.tpz
      #    unzip -j Godot_v4.0.2-stable_export_templates.tpz templates/android_source.zip -d .
      #    rm Godot_v4.0.2-stable_export_templates.tpz
      #    unzip android_source.zip -d android/build
      #    rm android_source.zip
      #    touch android/build/.gdignore
      #    echo "4.0.2.stable" > android/.build_version

      - name: Export
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.1.3-stable/Godot_v4.1.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: exports
          path: ${{ steps.export.outputs.archive_directory }}/*
